server:
  port: 0
  address: 127.0.0.1
spring:
  application:
    name: MY-FIRST-SERVICE
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka